[tox]
isolated_build = true
envlist =
  py36
  py37
  py38
  py39
  flake8
  black
  isort
  packaging

[testenv]
whitelist_externals = poetry
setenv =
  PYTHONDONTWRITEBYTECODE=1
  PYTHONHASHSEED=0
  PYTHONWARNINGS=ignore
commands =
  poetry config virtualenvs.create false --local
  poetry install -v --no-root
  poetry run pytest --cov

[testenv:flake8]
deps = flake8
commands = flake8 {toxinidir}

[testenv:black]
deps = black
commands = black . --check

[testenv:isort]
deps = isort
commands = isort . -c

[testenv:packaging]
skip_install = True
deps = twine
commands =
    poetry build
    twine check dist/*

[flake8]
max-line-length = 119
ignore =
    # do not assign a lambda expression, use a def
    E731
    # black handles following errors:
    E101
    E111
    E114
    E115
    E116
    E117
    E121
    E122
    E123
    E124
    E125
    E126
    E127
    E128
    E129
    E131
    E133
    E2
    E3
    E5
    E701
    E702
    E703
    E704
    W1
    W2
    W3
    W503
    W504
exclude =
    # git directory
    .git,
    # python artifacts
    __pycache__,
    # test artifacts
    .tox,
    # built artifacts
    build,
    dist,
    .eggs,
